### ISSUE TITLE
daemon

### ISSUE THREAD

**Issue by AlbanMinassian** [thomasdavis/seoserver#2]
Is it possible to run as daemon ? I see no option.
Thank

**Comment by thomasdavis** [comment]
If you are using linux simply typing `seoserver -p 4000 start > seoserver.log &` should start it as a background process

**Comment by AlbanMinassian** [comment]
it's work ! thank.

**Comment by RobGonda** [comment]
Seems like it dies after a while ... not sure if innactivity, not sure it stays in background after user logs off ... any chance it could be a real service? 
service seoserver [start|stop|restart|status] ?
