### ISSUE TITLE
Prevent seoserver from recording events in Google Analytics

### ISSUE THREAD

**Issue by heiskr** [thomasdavis/seoserver#9]
SEO server is excellent, but we've been having a ton of problems with our analytics data because the SEO server acts as if its a user when crawling the site. We've tried filtering it out in various ways, only to have the filter break. It might be good to have some sort of convention for filtering out traffic from the SEO server in Google Analytics. I realize everyone will have Google Analytics set up a bit differently, but there must be some sort of method to consistently take care of this issue.

**Comment by desmondmorris** [comment]
@heiskr any luck with this one?

**Comment by heiskr** [comment]
The solution we came up with was just to block out any user agent with Linux from going into our analytics.
